In [ ]:
# Numpy
# autor: TITHI PATEL

In [ ]:
# list NUMPY
import numpy as np
a=np.array([[1,2,3],[6,5,4],[9,8,7]])
# PRINTING THE ARRAY
print(a)
print(a.shape)

[[1 2 3]
 [6 5 4]
 [9 8 7]]
(3, 3)


In [ ]:
# built in type function
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
# tuple numpy
arr=np.array((1,3,5,7,9))
print(arr)

[1 3 5 7 9]


In [ ]:
# dimension check in numpy
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr.ndim)

3


In [ ]:
# copy and view
# copy
a=np.array([1,2,3,4,5])
x=a.copy()
print(a)
print(x)
a[0]=42
print("After changing element in a")
print(a)
print(x)

# view
print("-----------------------------------------------------------")
arr=np.array([1,2,3,4,5])
y=arr.view()
print(arr)
print(y)
arr[0]=42
print("After changing element in arr")
print(arr)
print(y)
print("-----------------------------------------------------------")
print(x.base)
print(y.base)


[1 2 3 4 5]
[1 2 3 4 5]
After changing element in a
[42  2  3  4  5]
[1 2 3 4 5]
-----------------------------------------------------------
[1 2 3 4 5]
[1 2 3 4 5]
After changing element in arr
[42  2  3  4  5]
[42  2  3  4  5]
-----------------------------------------------------------
None
[42  2  3  4  5]


In [ ]:
# shape in tuple
arr=np.array((1,2,3,4,5))
print(arr.shape)

(5,)


In [ ]:
# reshaping
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
reshapearr=arr.reshape(2,3,2)
print(reshapearr)
newarr=reshapearr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# iteration 
for x in np.nditer(reshapearr):
  print(x)


1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# joining arrays
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,1,12]])
arr=np.vstack((arr1,arr2))
print(arr)
# along coloumns
print("-----------------------------------------")
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)
# along row

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10  1 12]]
-----------------------------------------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10  1 12]]


In [ ]:
# splitting array
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# locating element
x=np.where(arr==4)
print(x)

(array([3]),)


In [ ]:
# search sorted
x=np.searchsorted(arr,4)
print(x)

3


In [ ]:
# sorting
arr=np.array([6,8,3,9])
print(np.sort(arr))

[3 6 8 9]


In [ ]:
arr=np.array(['Hello','Mr.X','Dude'])
print(np.sort(arr))

['Dude' 'Hello' 'Mr.X']


In [ ]:
# dataframe to numpy
import pandas as pd
df=pd.DataFrame(
    [[76,98,78],
    [99,69,78],
    [98,76,54],
    [5,6,8]],
    columns=['a','b','c']
)
print("Dataframe]\n",df)
arr=df.to_numpy()
print("Numpy\n",arr)

Dataframe]
     a   b   c
0  76  98  78
1  99  69  78
2  98  76  54
3   5   6   8
Numpy
 [[76 98 78]
 [99 69 78]
 [98 76 54]
 [ 5  6  8]]
